### PR TITLE
Convert to Python 3

### PR DESCRIPTION
**Pull request by justdave**
I'm attempting to resurrect this project because it was hella useful. :-)

And I needed it to run on a modern web server.

So here's a PR to make it run under Python 3.

A couple minor changes included here that are unrelated to the Python 3 conversion:
* All absolute links (/tool/bugzilla-schema/*) were made relative to make it easier to self-host at a different URL
* The links in the header/footer for Ravenbrook and the Ravenbrook tools page were removed. The shoutout to Ravenbrook for writing it is still in the main text on the front page.
* Both `make_schema_docs.py` and `pickle_schema.py` can now be run from the command line instead of having to use the python interpreter shell.

### CODE REVIEW

**Comment by justdave** [comment]
This is still a work in progress, I will only vouch for index.py and make_schema_doc.py so far.
This is now hosted at https://schema.bugzilla.org/

**Comment by NickBarnes** [comment]
Glad to see you're picking it up, Dave. I hope you can make it useful again. It's many years since I touched it, or used Bugzilla for that matter.

**Comment by justdave** [comment]
OK, I think this is ready for review/landing.  Any other py3 conversion gotchas we can catch as regular bug reports.

A rendered version of the modified updating.rst can be viewed at https://github.com/justdave/bugzilla-schema/blob/py3/updating.rst

I've updated the description at the top of this PR to indicate the addition of being able to run the two scripts from the command line instead of using the python interpreter.

**Comment by justdave** [comment]
PR won't let me request a review so I guess I have to depend on you seeing that comment. :-)

**Comment by NickBarnes** [comment]
Given that I never use Bugzilla any more, and don't really have the time or spoons to do a good job of this, it might make most sense for you to take ownership of this project on your fork of the repo. I can update the README here to point to yours.

**Comment by NickBarnes** [comment]
(have updated the README)

**Comment by justdave** [comment]
Sounds good to me, I will do so then.  If you're offically handing it over I'm going to put it into the actual Bugzilla repo instead of my own.  It will be here: https://github.com/bugzilla/bugzilla-schema

How much issue will I have with the Perforce copyright? Doesn't look like a standard license...

**Comment by UNAA008** [comment]
The Perforce licence was because Ravenbrook made this software as part of the P4DTI project that was at least part-funded by Perforce at the time.
I doubt that Perforce would have any objections to Bugzilla taking control of the work.
It seems to me that its natural home would be with Bugzilla.
As a director of Ravenbrook, I am happy for that to happen assuming that the material remains open source.
If we need to add any more formality, drop us mail at info@ravenbrook.com and I'll follow up.

**Comment by justdave** [comment]
Closing this out so it'll let me delete my branch. This was merged into the Bugzilla repo at https://github.com/bugzilla/bugzilla-schema

**Comment by NickBarnes** [comment]
I've updated the README to point directly to the Bugzilla project's repo.

**Pull request closed without merging**
